window.RATAN_CATALOGUE = [
  {
    "id": "inster-5107-sf",
    "name": "INSTER 5107-SF",
    "category": "Laminates",
    "spec": "Plain Color \u00b7 code 5107-SF \u00b7 sample approval required",
    "unit": "sheets",
    "image": "assets/inster/5107-sf.webp",
    "brand": "INSTER",
    "finish": "Plain Color",
    "sourcePage": 3,
    "sourceImage": "assets/inster/page-03.jpg",
    "catalogueId": "inster-2026-01-20",
    "availability": "Confirm with Ratan"
  },
  {
    "id": "inster-5101-sf",
    "name": "INSTER 5101-SF",
    "category": "Laminates",
    "spec": "Plain Color \u00b7 code 5101-SF \u00b7 sample approval required",
    "unit": "sheets",
    "image": "assets/inster/5101-sf.webp",
    "brand": "INSTER",
    "finish": "Plain Color",
    "sourcePage": 3,
    "sourceImage": "assets/inster/page-03.jpg",
    "catalogueId": "inster-2026-01-20",
    "availability": "Confirm with Ratan"
  },
  {
    "id": "inster-5100-sf",
    "name": "INSTER 5100-SF",
    "category": "Laminates",
    "spec": "Plain Color \u00b7 code 5100-SF \u00b7 sample approval required",
    "unit": "sheets",
    "image": "assets/inster/5100-sf.webp",
    "brand": "INSTER",
    "finish": "Plain Color",
    "sourcePage": 3,
    "sourceImage": "assets/inster/page-03.jpg",
    "catalogueId": "inster-2026-01-20",
    "availability": "Confirm with Ratan"
  },
  {
    "id": "inster-5126-sf",
    "name": "INSTER 5126-SF",
    "category": "Laminates",
    "spec": "Plain Color \u00b7 code 5126-SF \u00b7 sample approval required",
    "unit": "sheets",
    "image": "assets/inster/5126-sf.webp",
    "brand": "INSTER",
    "finish": "Plain Color",
    "sourcePage": 3,
    "sourceImage": "assets/inster/page-03.jpg",
    "catalogueId": "inster-2026-01-20",
    "availability": "Confirm with Ratan"
  },
  {
    "id": "inster-5186-sf",
    "name": "INSTER 5186-SF",
    "category": "Laminates",
    "spec": "Plain Color \u00b7 code 5186-SF \u00b7 sample approval required",
    "unit": "sheets",
    "image": "assets/inster/5186-sf.webp",
    "brand": "INSTER",
    "finish": "Plain Color",
    "sourcePage": 3,
    "sourceImage": "assets/inster/page-03.jpg",
    "catalogueId": "inster-2026-01-20",
    "availability": "Confirm with Ratan"
  },
  {
    "id": "inster-5134-sf",
    "name": "INSTER 5134-SF",
    "category": "Laminates",
    "spec": "Plain Color \u00b7 code 5134-SF \u00b7 sample approval required",
    "unit": "sheets",
    "image": "assets/inster/5134-sf.webp",
    "brand": "INSTER",
    "finish": "Plain Color",
    "sourcePage": 3,
    "sourceImage": "assets/inster/page-03.jpg",
    "catalogueId": "inster-2026-01-20",
    "availability": "Confirm with Ratan"
  },
  {
    "id": "inster-5180-sf",
    "name": "INSTER 5180-SF",
    "category": "Laminates",
    "spec": "Plain Color \u00b7 code 5180-SF \u00b7 sample approval required",
    "unit": "sheets",
    "image": "assets/inster/5180-sf.webp",
    "brand": "INSTER",
    "finish": "Plain Color",
    "sourcePage": 3,
    "sourceImage": "assets/inster/page-03.jpg",
    "catalogueId": "inster-2026-01-20",
    "availability": "Confirm with Ratan"
  },
  {
    "id": "inster-5125-sf",
    "name": "INSTER 5125-SF",
    "category": "Laminates",
    "spec": "Plain Color \u00b7 code 5125-SF \u00b7 sample approval required",
    "unit": "sheets",
    "image": "assets/inster/5125-sf.webp",
    "brand": "INSTER",
    "finish": "Plain Color",
    "sourcePage": 3,
    "sourceImage": "assets/inster/page-03.jpg",
    "catalogueId": "inster-2026-01-20",
    "availability": "Confirm with Ratan"
  },
  {
    "id": "inster-5075-sf",
    "name": "INSTER 5075-SF",
    "category": "Laminates",
    "spec": "Suede Finish \u00b7 code 5075-SF \u00b7 sample approval required",
    "unit": "sheets",
    "image": "assets/inster/5075-sf.webp",
    "brand": "INSTER",
    "finish": "Suede Finish",
    "sourcePage": 8,
    "sourceImage": "assets/inster/page-08.jpg",
    "catalogueId": "inster-2026-01-20",
    "availability": "Confirm with Ratan"
  },
  {
    "id": "inster-5045-sf",
    "name": "INSTER 5045-SF",
    "category": "Laminates",
    "spec": "Suede Finish \u00b7 code 5045-SF \u00b7 sample approval required",
    "unit": "sheets",
    "image": "assets/inster/5045-sf.webp",
    "brand": "INSTER",
    "finish": "Suede Finish",
    "sourcePage": 8,
    "sourceImage": "assets/inster/page-08.jpg",
    "catalogueId": "inster-2026-01-20",
    "availability": "Confirm with Ratan"
  },
  {
    "id": "inster-5082-sf",
    "name": "INSTER 5082-SF",
    "category": "Laminates",
    "spec": "Suede Finish \u00b7 code 5082-SF \u00b7 sample approval required",
    "unit": "sheets",
    "image": "assets/inster/5082-sf.webp",
    "brand": "INSTER",
    "finish": "Suede Finish",
    "sourcePage": 18,
    "sourceImage": "assets/inster/page-18.jpg",
    "catalogueId": "inster-2026-01-20",
    "availability": "Confirm with Ratan"
  },
  {
    "id": "inster-5036-sf",
    "name": "INSTER 5036-SF",
    "category": "Laminates",
    "spec": "Suede Finish \u00b7 code 5036-SF \u00b7 sample approval required",
    "unit": "sheets",
    "image": "assets/inster/5036-sf.webp",
    "brand": "INSTER",
    "finish": "Suede Finish",
    "sourcePage": 18,
    "sourceImage": "assets/inster/page-18.jpg",
    "catalogueId": "inster-2026-01-20",
    "availability": "Confirm with Ratan"
  },
  {
    "id": "inster-5024-sf",
    "name": "INSTER 5024-SF",
    "category": "Laminates",
    "spec": "Suede Finish \u00b7 code 5024-SF \u00b7 sample approval required",
    "unit": "sheets",
    "image": "assets/inster/5024-sf.webp",
    "brand": "INSTER",
    "finish": "Suede Finish",
    "sourcePage": 18,
    "sourceImage": "assets/inster/page-18.jpg",
    "catalogueId": "inster-2026-01-20",
    "availability": "Confirm with Ratan"
  },
  {
    "id": "inster-5040-sf",
    "name": "INSTER 5040-SF",
    "category": "Laminates",
    "spec": "Suede Finish \u00b7 code 5040-SF \u00b7 sample approval required",
    "unit": "sheets",
    "image": "assets/inster/5040-sf.webp",
    "brand": "INSTER",
    "finish": "Suede Finish",
    "sourcePage": 18,
    "sourceImage": "assets/inster/page-18.jpg",
    "catalogueId": "inster-2026-01-20",
    "availability": "Confirm with Ratan"
  }
];
