const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const {JSDOM}=require('jsdom');const root=path.resolve(__dirname,'..');
function load(html,scripts){const dom=new JSDOM(fs.readFileSync(path.join(root,html),'utf8'),{runScripts:'outside-only',url:'https://example.com/'}),w=dom.window;w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'));};w.HTMLElement.prototype.scrollIntoView=function(){};w.matchMedia=()=>({matches:true});w.requestAnimationFrame=fn=>fn();for(const s of scripts)w.eval(fs.readFileSync(path.join(root,s),'utf8'));return dom;}
(async()=>{const dom=load('index.html',['config.js','catalogue-data.js','experience.js','script.js']),w=dom.window,d=w.document,$=s=>d.querySelector(s),$$=s=>[...d.querySelectorAll(s)];await new Promise(r=>setTimeout(r,0));let calls=[],fail=false,wrongId=false;
w.fetch=async (url,opts)=>{const p=Object.fromEntries(opts.body);calls.push(p);if(fail)throw new TypeError('offline');return{ok:true,json:async()=>({ok:true,requestId:wrongId?'wrong':p.requestId,reference:'RATAN-TEAK-12345678'})};};
const form=$('#enquiry-form');function fill(k,v){form.elements['entry_'+k].value=v;}const submit=async()=>{form.dispatchEvent(new w.Event('submit',{cancelable:true}));await new Promise(r=>setTimeout(r,0));};const close=()=>$$('dialog').forEach(x=>x.close());
assert.equal($$('.section-drawer').length,6);assert.equal($$('.widget-grid .journey-card').length,2);assert.equal($$('#products .product').length,12);assert(!d.body.textContent.includes('receipt opens'));assert.equal(form.getAttribute('target'),null);
$('.ask-ratan').click();assert(form.elements.consent.checked);assert.equal(form.elements.entry_phone.maxLength,10);fill('phone','9876543210123456');assert(!form.checkValidity());fill('phone','9876543210');fill('requirement','paint');assert(form.checkValidity());await submit();assert.equal(calls.at(-1).phone,'+919876543210');assert($('#received-dialog').open);assert($('#received-dialog').textContent.includes('RATAN-TEAK'));
close();$('[data-enquiry="Supplier application"]').click();fill('business','TEST ONLY');fill('phone','9876543210');fill('location','Ahmedabad');fill('requirement','paint');assert(form.checkValidity());await submit();assert.equal(calls.at(-1).business,'TEST ONLY');assert.equal(calls.at(-1).kind,'Supplier application');
close();$('[data-enquiry="Bulk sourcing"]').click();assert(!form.elements.entry_timeline.required);fill('name','TEST');fill('phone','9876543210');fill('requirement','ply');fill('quantity','20 sheets');fill('location','Ahmedabad');await submit();assert.equal(calls.at(-1).kind,'Bulk sourcing');
close();$('.bundle button').click();$('#quote-list').click();assert.equal($$('#enquiry-fields textarea').length,0);fill('name','TEST');fill('phone','9876543210');fail=true;await submit();const id=form.elements.requestId.value;assert($('#enquiry-dialog').open);assert(!$('#received-dialog').open);assert($('#form-status').textContent.includes('Retry safely'));fail=false;await submit();assert.equal(form.elements.requestId.value,id);assert($('#received-dialog').open);
close();$('.ask-ratan').click();fill('phone','9876543210');fill('requirement','paint');wrongId=true;await submit();assert(!$('#received-dialog').open);assert($('#enquiry-dialog').open);wrongId=false;
form.elements.entry_country.value='1';form.elements.entry_country.dispatchEvent(new w.Event('change'));fill('phone','2025550101');assert.equal(w.RatanExperience.phoneValue(form),'+12025550101');form.elements.entry_country.value='';form.elements.entry_country.dispatchEvent(new w.Event('change'));assert(form.elements.entry_dial.required);fill('dial','81');form.elements.entry_dial.dispatchEvent(new w.Event('input'));assert.equal(form.elements.entry_phone.maxLength,13);
assert.equal($$('a[href*="wa.me"] .wa-icon').length,$$('a[href*="wa.me"]').length);assert(!/[→↗←↓]/.test(d.body.textContent));assert(JSON.parse(w.localStorage.getItem('ratan-shortlist-v1')).length>0);dom.window.close();
const bd=load('brochure/index.html',['brochure/catalogue.js','brochure/studio.js']),bw=bd.window,doc=bw.document;assert.equal(doc.querySelectorAll('.page').length,5);assert.equal(doc.querySelectorAll('.option-editor').length,3);assert.equal(doc.querySelectorAll('.option-editor select option').length,45);const nums=[...doc.querySelector('.option-editor').querySelectorAll('input[type=number]')];[10,100,18,50].forEach((v,i)=>{nums[i].value=v;nums[i].dispatchEvent(new bw.Event('input',{bubbles:true}));});assert(doc.querySelector('.money').textContent.includes('1,230.00'));doc.querySelector('.option-editor select').value='0';doc.querySelector('.option-editor select').dispatchEvent(new bw.Event('change'));assert(doc.querySelector('#preview').textContent.includes('INSTER 5107-SF'));assert(doc.querySelector('#preview img').getAttribute('src').startsWith('assets/inster/'));assert(!doc.querySelector('#reviewed').checked);bd.window.close();console.log('PASS: enquiry schemas, phone limits, inline receipt, failed/mismatched responses, idempotent retry, icons, disclosures, persistence, brochure calculations & catalogue selections');})().catch(e=>{console.error(e);process.exit(1);});
