'use strict';
const form=document.getElementById('editor'),preview=document.getElementById('preview'),editors=document.getElementById('option-editors'),status=document.getElementById('status');
let options=[],cover='';
const templates={laminate:['Woodgrain · option A','Woodgrain · option B','Woodgrain · option C'],boards:['Board · value option','Board · upgraded specification'],custom:['Your first option','Your second option']};
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const round=n=>Math.round((n+Number.EPSILON)*100)/100;
function calculate(o){const base=round(Number(o.quantity)*Number(o.price)),tax=round(base*Number(o.tax)/100);return{base,tax,total:round(base+tax+Number(o.shipping))};}
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:form.elements.currency.value}).format(n);
function draft(){return{version:1,...Object.fromEntries(new FormData(form)),cover,options};}
function field(parent,label,key,value,type,change){const l=el('label',label),i=el(type==='textarea'?'textarea':'input');if(type!=='textarea')i.type=type;i.value=value;i.required=true;if(type==='number'){i.min=key==='quantity'?'0.01':'0';i.max=key==='tax'?'100':'100000000';i.step='0.01';}else{i.maxLength=key==='spec'?350:100;}i.oninput=()=>{change(i.value);form.querySelector('#reviewed').checked=false;render();};l.append(i);parent.append(l);}
function edit(){editors.replaceChildren();options.forEach((o,index)=>{const box=el('div',undefined,'option-editor');box.append(el('h3','Option '+(index+1)));const pickLabel=el('label','Use a reviewed INSTER design'),pick=el('select');pick.append(new Option('Custom / uploaded image',''));(window.BROCHURE_DESIGNS||[]).forEach((p,j)=>pick.append(new Option(p.name,String(j))));pick.value=String((window.BROCHURE_DESIGNS||[]).findIndex(p=>p.image===o.image));pick.onchange=()=>{if(pick.value==='')return;const p=window.BROCHURE_DESIGNS[Number(pick.value)];o.name=p.name;o.spec=p.spec+' · catalogue page '+p.sourcePage;o.image=p.image;form.querySelector('#reviewed').checked=false;edit();render();};pickLabel.append(pick);box.append(pickLabel);field(box,'Material / design','name',o.name,'text',v=>o.name=v);field(box,'Specification, shade code & finish','spec',o.spec,'textarea',v=>o.spec=v);const row=el('div',undefined,'row');field(row,'Quantity','quantity',o.quantity,'number',v=>o.quantity=v);field(row,'Unit (sheet, piece…)','unit',o.unit,'text',v=>o.unit=v);box.append(row);field(box,'Unit rate, excluding tax','price',o.price,'number',v=>o.price=v);const charges=el('div',undefined,'row');field(charges,'Tax % (verify for item)','tax',o.tax,'number',v=>o.tax=v);field(charges,'Delivery, tax-inclusive','shipping',o.shipping,'number',v=>o.shipping=v);box.append(charges);field(box,'Availability / lead time','eta',o.eta,'text',v=>o.eta=v);const label=el('label','Material photograph / swatch'),upload=el('input');upload.type='file';upload.accept='image/jpeg,image/png,image/webp';upload.onchange=()=>readImage(upload,f=>{o.image=f;render();});label.append(upload);box.append(label);const remove=el('button','Remove option');remove.type='button';remove.onclick=()=>{if(options.length===1){status.textContent='Keep at least one option.';return;}options.splice(index,1);edit();render();};box.append(remove);editors.append(box);});}
function add(name='New material option'){options.push({name,spec:'Confirm brand, code, thickness and size',quantity:1,unit:'sheet',price:'',tax:0,shipping:0,eta:'To be confirmed',image:''});}
function brand(page,index){const b=el('div',undefined,'page-brand');b.append(el('span','RATAN.'),el('small','MATERIAL PROPOSAL / '+String(index).padStart(2,'0')));page.append(b);}
function render(){const d=draft();preview.replaceChildren();const coverPage=el('article',undefined,'page cover');if(cover){const im=el('img');im.src=cover;im.alt='Owner-supplied project reference photograph';coverPage.append(im);}brand(coverPage,1);coverPage.append(el('p','PREPARED FOR '+(d.customer||'YOUR CUSTOMER'),'eyebrow'),el('h2',d.title),el('p',d.brief||'Your material requirement, thoughtfully brought together.','brief'),el('p',(d.reference||'ENQUIRY REFERENCE')+' / REV '+d.revision,'reference'),el('p',d.caption,'caption'),el('p','Ratan Enterprises · Ahmedabad\n+91 98253 38851','page-foot'));preview.append(coverPage);
  const compare=el('article',undefined,'page');brand(compare,2);compare.append(el('p','YOUR CHOICE, AT A GLANCE','eyebrow'),el('h2','Different options.\nOne clear comparison.'));const table=el('table',undefined,'comparison'),head=el('tr');['Option','Quantity','Landed total'].forEach(t=>head.append(el('th',t)));table.append(head);options.forEach((o,i)=>{const row=el('tr');row.append(el('td',String.fromCharCode(65+i)+' · '+o.name),el('td',o.quantity+' '+o.unit),el('td',o.price===''?'Rate pending':money(calculate(o).total)));table.append(row);});compare.append(table,el('p','Choose one alternative. These totals are not added together. Each includes the entered item tax and tax-inclusive delivery.','hint'),el('h3','Your brief'),el('p',d.brief,'brief'),el('h3','Before you decide'),el('p',d.terms,'terms'),el('p','Valid until: '+(d.validUntil||'Not set')+' · Delivery: '+(d.delivery||'To confirm'),'page-foot'));preview.append(compare);
  options.forEach((o,i)=>{const page=el('article',undefined,'page');brand(page,i+3);page.append(el('p','OPTION '+String.fromCharCode(65+i),'option-label'),el('h2',o.name));if(o.image){const im=el('img');im.className='swatch';im.src=o.image;im.alt=o.name;page.append(im);}else page.append(el('div','Add a material photograph or catalogue swatch','image-placeholder'));page.append(el('p',o.spec));const c=calculate(o),dl=el('dl');[['Quantity',o.quantity+' '+o.unit],['Unit rate',o.price===''?'Pending':money(Number(o.price))],['Material subtotal',o.price===''?'Pending':money(c.base)],['Tax ('+o.tax+'%)',o.price===''?'Pending':money(c.tax)],['Delivery incl. tax',money(Number(o.shipping))],['Availability',o.eta]].forEach(([k,v])=>dl.append(el('dt',k),el('dd',v)));page.append(dl);const total=el('div',undefined,'money');total.append(el('small','LANDED TOTAL · OPTION '+String.fromCharCode(65+i)),el('strong',o.price===''?'Rate pending':money(c.total)));page.append(total,el('p','To select, reply to Ratan with '+(d.reference||'your reference')+', revision '+d.revision+' and Option '+String.fromCharCode(65+i)+'. Final acceptance is confirmed by the Ratan desk.','page-foot'));preview.append(page);});}
function readImage(input,done){const f=input.files[0];if(!f)return;if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>5*1024*1024){status.textContent='Choose a JPG, PNG or WebP under 5 MB.';return;}const reader=new FileReader();reader.onload=()=>{done(reader.result);form.querySelector('#reviewed').checked=false;};reader.readAsDataURL(f);}
document.getElementById('cover-upload').onchange=e=>readImage(e.target,v=>{cover=v;render();});
document.getElementById('add-option').onclick=()=>{if(options.length>=6){status.textContent='Keep comparisons focused: maximum six alternatives.';return;}add();edit();render();};
document.getElementById('apply-template').onclick=()=>{if(!confirm('Replace the current material options with this template?'))return;options=[];templates[document.getElementById('template').value].forEach(n=>add(n));edit();render();};
form.addEventListener('input',e=>{if(e.target.id!=='reviewed')form.querySelector('#reviewed').checked=false;render();});form.onsubmit=async e=>{e.preventDefault();if(!form.reportValidity())return;const button=form.querySelector('[type=submit]');button.disabled=true;status.textContent='Preparing your PDF…';try{const loadImage=async src=>{const im=new Image();im.src=src;await im.decode();const canvas=document.createElement('canvas');canvas.width=1400;canvas.height=630;const ctx=canvas.getContext('2d');ctx.fillStyle='#e4e9df';ctx.fillRect(0,0,1400,630);const scale=Math.min(1400/im.width,630/im.height);ctx.drawImage(im,(1400-im.width*scale)/2,(630-im.height*scale)/2,im.width*scale,im.height*scale);return canvas.toDataURL('image/jpeg',.9);};const pdf=await buildRatanPDF(draft(),window.jspdf.jsPDF,loadImage);pdf.save((form.elements.reference.value+'-rev-'+form.elements.revision.value).replace(/[^a-zA-Z0-9-]/g,'_')+'.pdf');status.textContent='Your PDF is ready. Check your downloads. Keep the private draft to revise it later.';}catch(error){status.textContent='PDF not exported: '+error.message;}finally{button.disabled=false;}};
document.getElementById('save-draft').onclick=()=>{const a=el('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(draft(),null,2)],{type:'application/json'}));a.download=(form.elements.reference.value||'ratan-draft').replace(/[^a-zA-Z0-9-]/g,'_')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);status.textContent='Private draft downloaded. Keep it out of public repositories.';};
document.getElementById('import').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>35*1024*1024)throw Error('File too large.');const d=JSON.parse(await f.text());if(!d||typeof d!=='object')throw Error('Invalid draft.');['reference','customer','brief','revision','validUntil','title','terms','delivery'].forEach(k=>{if(typeof d[k]==='string'&&form.elements[k])form.elements[k].value=d[k].slice(0,k==='brief'||k==='terms'?1500:180);});if(['INR','USD','AED','GBP'].includes(d.currency))form.elements.currency.value=d.currency;const safeImage=v=>typeof v==='string'&&(/^data:image\/(png|jpeg|webp);base64,/.test(v)||(window.BROCHURE_DESIGNS||[]).some(p=>p.image===v))?v:'';cover=safeImage(d.cover);if(Array.isArray(d.options)&&d.options.length){options=d.options.slice(0,6).map(o=>({name:String(o.name||'Material').slice(0,100),spec:String(o.spec||'').slice(0,350),unit:String(o.unit||'sheet').slice(0,30),eta:String(o.eta||'To confirm').slice(0,100),quantity:Math.min(100000000,Math.max(.01,Number(o.quantity)||1)),price:o.price===''?'':Math.min(100000000,Math.max(0,Number(o.price)||0)),tax:Math.min(100,Math.max(0,Number(o.tax)||0)),shipping:Math.min(100000000,Math.max(0,Number(o.shipping)||0)),image:safeImage(o.image)}));}edit();render();form.querySelector('#reviewed').checked=false;status.textContent='Imported privately. Review the quote before exporting.';}catch(error){status.textContent='Could not import: '+error.message;}};
templates.laminate.forEach(n=>add(n));edit();render();
