'use strict';
const form=document.getElementById('editor'),preview=document.getElementById('preview'),editors=document.getElementById('option-editors'),status=document.getElementById('status');
let options=[],cover='',sourceItems=[],excluded=[],pdfObject=null,pdfURL='',previewRevision=0;
const templates={laminate:['Woodgrain · option A','Woodgrain · option B','Woodgrain · option C'],boards:['Board · value option','Board · upgraded specification'],custom:['Your first option','Your second option']};
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const round=n=>Math.round((n+Number.EPSILON)*100)/100;
function calculate(o){const base=round(Number(o.quantity)*Number(o.price)),tax=round(base*Number(o.tax)/100);return{base,tax,total:round(base+tax+Number(o.shipping))};}
function draft(){return{version:2,...Object.fromEntries(new FormData(form)),cover,options,sourceItems,excluded};}
function render(){previewRevision++;pdfObject=null;if(pdfURL){URL.revokeObjectURL(pdfURL);pdfURL='';}preview.replaceChildren(el('h2','Preview the actual PDF'),el('p','Choose Preview PDF below when ready. The file shown here is the exact file you approve and download. Any edit invalidates that approval.'));form.querySelector('#reviewed').checked=false;document.getElementById('coverage').textContent=sourceItems.length?sourceItems.length+' requested lines · '+options.filter(o=>o.requestKey).length+' included · '+excluded.length+' explicitly excluded. Original brief remains below.':'Manual proposal. Load an enquiry to track requested-item coverage.';}
function field(parent,label,key,value,type,change){const l=el('label',label),i=el(type==='textarea'?'textarea':'input');if(type!=='textarea')i.type=type;i.value=value??'';i.required=true;if(type==='number'){i.min=key==='quantity'?'0.01':'0';i.max=key==='tax'?'100':'100000000';i.step='0.01';}else i.maxLength=key==='spec'?1000:500;i.oninput=()=>{change(i.value);render();};l.append(i);parent.append(l);}
function edit(){editors.replaceChildren();options.forEach((o,index)=>{const box=el('div',undefined,'option-editor');box.append(el('h3',(form.elements.mode.value==='items'?'Item ':'Option ')+(index+1)));if(o.requestedText)box.append(el('p','Customer requested: '+o.requestedText,'source-line'));
const pickLabel=el('label','Use a reviewed INSTER design'),pick=el('select');pick.append(new Option('Custom / uploaded image',''));(window.BROCHURE_DESIGNS||[]).forEach((p,j)=>pick.append(new Option(p.name,String(j))));const selected=(window.BROCHURE_DESIGNS||[]).findIndex(p=>p.image===o.image);pick.value=selected<0?'':String(selected);pick.onchange=()=>{if(pick.value==='')return;const p=window.BROCHURE_DESIGNS[Number(pick.value)];o.name=p.name;o.spec=p.spec+' · catalogue page '+p.sourcePage;o.image=p.image;edit();render();};pickLabel.append(pick);box.append(pickLabel);
field(box,'Material / design','name',o.name,'text',v=>o.name=v);field(box,'Specification, shade code & finish','spec',o.spec,'textarea',v=>o.spec=v);const row=el('div',undefined,'row');field(row,'Quantity','quantity',o.quantity,'number',v=>o.quantity=v);field(row,'Unit (sheet, piece…)','unit',o.unit,'text',v=>o.unit=v);box.append(row);field(box,'Unit rate, excluding tax','price',o.price,'number',v=>o.price=v);const charges=el('div',undefined,'row');field(charges,'Tax % (verify for item)','tax',o.tax,'number',v=>o.tax=v);field(charges,'Delivery allocation, tax-inclusive','shipping',o.shipping,'number',v=>o.shipping=v);box.append(charges);field(box,'Availability / lead time','eta',o.eta,'text',v=>o.eta=v);if(o.priceSuggestion)box.append(el('p',o.priceSuggestion,'hint'));const label=el('label','Material photograph / swatch'),upload=el('input');upload.type='file';upload.accept='image/jpeg,image/png,image/webp';upload.onchange=()=>readImage(upload,f=>{o.image=f;render();});label.append(upload);box.append(label);const remove=el('button',o.requestKey?'Exclude requested item':'Remove option');remove.type='button';remove.onclick=()=>{if(options.length===1){status.textContent='Keep at least one quoted item.';return;}if(o.requestKey){const reason=prompt('Why is this requested item excluded? This reason will be included in the PDF.');if(!reason?.trim())return;excluded.push({requestKey:o.requestKey,text:o.requestedText,reason:reason.trim()});}options.splice(index,1);edit();render();};box.append(remove);editors.append(box);});}
function add(name='New material option'){options.push({name,spec:'Confirm brand, code, thickness and size',quantity:1,unit:'sheet',price:'',tax:'',shipping:'',eta:'To be confirmed',image:''});}
function readImage(input,done){const f=input.files[0];if(!f)return;if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>5*1024*1024){status.textContent='Choose a JPG, PNG or WebP under 5 MB.';return;}const reader=new FileReader();reader.onload=()=>{done(reader.result);render();};reader.readAsDataURL(f);}
document.getElementById('cover-upload').onchange=e=>readImage(e.target,v=>{cover=v;});
document.getElementById('add-option').onclick=()=>{if(options.length>=100){status.textContent='Maximum 100 lines. Split larger proposals; no lines are discarded.';return;}add();edit();render();};
document.getElementById('apply-template').onclick=()=>{if(sourceItems.length){status.textContent='Templates cannot replace a loaded customer list. Add individual alternatives instead.';return;}if(!confirm('Replace the current material options with this template?'))return;options=[];templates[document.getElementById('template').value].forEach(n=>add(n));edit();render();};
form.addEventListener('input',e=>{if(e.target.id!=='reviewed')render();});form.elements.mode.addEventListener('change',()=>{if(sourceItems.length)form.elements.mode.value='items';edit();render();});
async function loadImage(src,box){const im=new Image();im.crossOrigin='anonymous';im.src=new URL(src,document.baseURI).href;await im.decode();const canvas=document.createElement('canvas');const crop=box.fit==='cover';canvas.width=crop?1600:Math.min(im.naturalWidth,1600);canvas.height=crop?Math.round(1600*box.height/box.width):Math.round(im.naturalHeight*canvas.width/im.naturalWidth);const ctx=canvas.getContext('2d');ctx.fillStyle='#f6f3ec';ctx.fillRect(0,0,canvas.width,canvas.height);const scale=crop?Math.max(canvas.width/im.naturalWidth,canvas.height/im.naturalHeight):canvas.width/im.naturalWidth;ctx.drawImage(im,(canvas.width-im.naturalWidth*scale)/2,(canvas.height-im.naturalHeight*scale)/2,im.naturalWidth*scale,im.naturalHeight*scale);return{data:canvas.toDataURL('image/jpeg',.92),width:canvas.width,height:canvas.height};}
function validateCoverage(){if(sourceItems.some(s=>!options.some(o=>o.requestKey===s.requestKey)&&!excluded.some(e=>e.requestKey===s.requestKey&&e.reason)))throw Error('A requested item is unaccounted for. Include it or record an exclusion reason.');}
document.getElementById('preview-pdf').onclick=async()=>{const rev=previewRevision;status.textContent='Building the exact PDF preview…';try{validateCoverage();const fonts=await loadRatanFonts();const result=await buildRatanPDF(draft(),window.jspdf.jsPDF,loadImage,fonts);if(rev!==previewRevision){status.textContent='The draft changed. Preview again when your edits are finished.';return;}pdfObject=result;pdfURL=URL.createObjectURL(result.output('blob'));const frame=el('iframe');frame.title='Exact PDF preview';frame.src=pdfURL;preview.replaceChildren(frame);const open=el('a','Open full PDF preview');open.href=pdfURL;open.target='_blank';open.rel='noopener';preview.append(open);status.textContent='Preview ready. Review every page, then approve and download. Pending fields still block download.';}catch(e){status.textContent=e.message;}};
form.onsubmit=e=>{e.preventDefault();if(!form.reportValidity())return;try{validateCoverage();if(!pdfObject)throw Error('Preview the current PDF before approving it.');pdfObject.save((form.elements.reference.value+'-rev-'+form.elements.revision.value).replace(/[^a-zA-Z0-9-]/g,'_')+'.pdf');status.textContent='Approved PDF downloaded: exactly the previewed file. Nothing has been sent to the customer.';}catch(e){status.textContent=e.message;}};
document.getElementById('save-draft').onclick=()=>{const a=el('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(draft(),null,2)],{type:'application/json'}));a.download=(form.elements.reference.value||'ratan-draft').replace(/[^a-zA-Z0-9-]/g,'_')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);status.textContent='Private draft downloaded. Keep it out of public repositories.';};
function importData(data){if(!data||typeof data!=='object')throw Error('Invalid draft.');const d=Array.isArray(data.options)?data:RatanRequirements.fromEnquiry(data);if(d.options.length>100)throw Error('Import stopped: more than 100 items. Nothing has been discarded.');const safeImage=v=>typeof v==='string'&&(/^data:image\/(png|jpeg|webp);base64,/.test(v)||(window.BROCHURE_DESIGNS||[]).some(p=>p.image===v))?v:'';['reference','customer','brief','revision','validUntil','title','terms','delivery','caption'].forEach(k=>{if(typeof d[k]==='string'&&form.elements[k])form.elements[k].value=d[k];});if(['INR','USD','AED','GBP'].includes(d.currency))form.elements.currency.value=d.currency;form.elements.mode.value=d.mode==='items'?'items':'alternatives';cover=safeImage(d.cover);options=d.options.map((o,i)=>({...o,name:String(o.name||'Material'),spec:String(o.spec||''),unit:String(o.unit||''),eta:String(o.eta||'To confirm'),quantity:o.quantity??'',price:o.price??'',tax:o.tax??'',shipping:o.shipping??'',image:safeImage(o.image)}));sourceItems=Array.isArray(d.sourceItems)?d.sourceItems:(d.mode==='items'?options.map(o=>({requestKey:o.requestKey,text:o.requestedText})):[]);excluded=Array.isArray(d.excluded)?d.excluded:[];edit();render();status.textContent='Loaded '+options.length+' lines. Review quantities, units and full original brief before pricing.';}
document.getElementById('import').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>35*1024*1024)throw Error('File too large.');if(!confirm('Replace the current draft with this private file?'))return;importData(JSON.parse(await f.text()));}catch(error){status.textContent='Could not import: '+error.message;}};
document.getElementById('lookup-reference').onclick=async()=>{try{if(!confirm('Load this reference and replace the current draft? Download the draft first if needed.'))return;status.textContent='Checking staff access and loading enquiry…';const d=await RatanStaff.call('enquiry',form.elements.reference.value.trim());importData(d);}catch(e){status.textContent=e.message;}};
document.getElementById('fetch-prices').onclick=async()=>{try{const result=await RatanStaff.call('prices',options.map(o=>({name:o.name,spec:o.spec,unit:o.unit,currency:form.elements.currency.value})));let applied=0;for(const s of result.suggestions){const o=options[s.index];if(!o)continue;if(s.matched&&o.price===''){o.price=s.price;o.tax=s.tax;o.priceSuggestion='PriceBook suggestion valid through '+s.validUntil+'; confirm availability and rate before approval.';applied++;}else o.priceSuggestion=s.matched?'Existing manual rate retained.':s.reason;}edit();render();status.textContent=applied+' current exact-match rates suggested. Manual prices were not overwritten.';}catch(e){status.textContent=e.message;}};
window.RatanStudio={importData,draft,calculate};
templates.laminate.forEach(n=>add(n));edit();render();
if(RatanStaff.available())RatanStaff.call('session').then(s=>document.getElementById('staff-state').textContent='Signed in: '+s.email).catch(e=>{form.hidden=true;status.textContent=e.message;});
